### ISSUE TITLE
Feature request: Filter incoming pings by domain (disallow-list)

### ISSUE THREAD

**Issue by HongPong** [dartiss/no-self-ping#26]
Hi, as I understand this it is preventing outgoing pings to the listed domains from being emitted. However could it be added to reject / trash incoming pings that match a disallow list? 

eg using this hook https://developer.wordpress.org/reference/hooks/pre_comment_approved/

**Comment by dartiss** [comment]
Hi!

T[ake a look at this screenshot](https://ps.w.org/no-self-ping/assets/screenshot-1.png?rev=1816443) from the plugin settings - does this not achieve what you're after? You can add additional URLs that will then not be allowed.

**Comment by dartiss** [comment]
No response - assuming this is already covered by the existing settings.
